package webservice

func registerBaselineHintAliases() {
	// Extra baseline aliases commonly seen in container names/domains.
	addHintAlias("nginx-proxy-manager", "npm")
	addHintAlias("mqtt", "mosquitto")
	addHintAlias("nodered", "node-red")
	addHintAlias("codeserver", "code-server")
	addHintAlias("jdownloader", "jdownloader-2")
	addHintAlias("nzbhydra", "nzbhydra2")
	addHintAlias("rtorrent", "rutorrent")
	addHintAlias("crafty", "crafty-controller")
	addHintAlias("crafty", "crafty-4")
	addHintAlias("airsonic", "airsonic-advanced")
	addHintAlias("changedetection", "changedetection-io")
	addHintAlias("changedetection", "changedetectionio")
	addHintAlias("wg-easy", "wg_easy")
	addHintAlias("ddns-updater", "ddns")
	addHintAlias("cloudflare-ddns", "cloudflare-ddns-updater")
	addHintAlias("stirling-pdf", "s-pdf")
	addHintAlias("tandoor", "recipes")
	addHintAlias("firefly-iii", "fireflyiii")
	addHintAlias("woodpecker", "woodpecker-ci")
	addHintAlias("zwavejs", "zwave-js-ui")
	addHintAlias("zwavejs", "zwave-js")
	addHintAlias("wyze-bridge", "wyze")
	addHintAlias("double-take", "doubletake")
	addHintAlias("guacamole", "apache-guacamole")
	addHintAlias("stash", "stashapp")
	addHintAlias("jdownloader", "jd")
	addHintAlias("jdownloader", "jdownloader2")
	addHintAlias("codeserver", "vscode")
	addHintAlias("proxmox-backup", "pbs")
	addHintAlias("truenas", "truenas-scale")
	addHintAlias("truenas", "truenas-core")
	addHintAlias("synology", "dsm")
	addHintAlias("synology", "diskstation")
	addHintAlias("qnap", "qts")
	addHintAlias("pfsense", "pf-sense")
	addHintAlias("opnsense", "opn-sense")
}
